server:
  port: 80
# 应用名称
spring:
  application:
    name: cloud-order-service


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1113/eureka/


