server:
  port: 8980

spring:
  application:
    name: cloud-pure-zk-consumer
dubbo:
  application:
    name: cloud-pure-zk-consumer
  registry:
    address: localhost:2181
    protocol: zookeeper
  monitor:
    protocol: registry



