# 应用服务 WEB 访问端口
server:
  port: 8333
# 应用名称
spring:
  application:
    name: cloud-zk-provider

dubbo:
  # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
  # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
  application:
    name: cloud-zk-provider
  registry:
    address: localhost:2181
    protocol: zookeeper
  protocol:
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    name: dubbo
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://localhost:2181
    group: dubbo
  # dubbo 服务扫描基准包
  scan:
    base-packages: com.sohu.cms.springcloud.cloudzkprovider


