spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: passw0rd
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sohu.cms.springcloud.cloud.provider.payment8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1113/eureka/
    # 表示是否将自己注册进Eureka Server 默认为true
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的注册信息，默认为true。集群必须设置为true才能配合Ribbon使用LB
    fetch-registry: true

