server:
  port: 8004
# 应用名称
spring:
  application:
    name: payment-zk-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/football?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: passw0rd

  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sohu.cms.springcloud.entities


